### PR TITLE
No such method as '5'

### PR DESCRIPTION
**Pull request by Krunniee**
Just another fix ;)

### CODE REVIEW

**Comment by Krunniee** [comment]
If you add me as a contributor to this repository I can help with a majority of the bugs in the bot and add new features.

**Comment by mattsilver1** [comment]
Sure, mind joining this server https://discord.gg/srf3NX real quick so I can give you appropriate roles?

**Comment by Krunniee** [comment]
I am at school currently on a laptop, I'll do it once I get on my laptop at home.

**Comment by mattsilver1** [comment]
Alright, nice. Ping me or a Council member and let us know and we'll give you tester/contributor roles.

**Comment by Krunniee** [comment]
Alright, thank you.

**Pull request merged**
