### PR TITLE
bug fixes

### PR DESCRIPTION
**Pull request by Krunniee**
Add bug fixes such as spelling errors and more.

### CODE REVIEW

**Comment by mattsilver1** [comment]
I already fixed them when you made this lol

**Comment by Krunniee** [comment]
Not the spelling. It was set as `FC` and not `FCC` :stuck_out_tongue:

**Comment by mattsilver1** [comment]
I fixed that as well kek

**Comment by Krunniee** [comment]
It didn't show on my end, sadly o.O

**Pull request closed without merging**
