### PR TITLE
Update whois.js

### PR DESCRIPTION
**Pull request by matthew119427**
# Discord Information #
Discord Username w/ Discriminator:
Discord User ID:

**What is this Pull Request for?**

**Are you fixing an issue, if so, what is it?**

**What changes are being made in this pull request?**

**Put any additional details below**

### CODE REVIEW

**Comment by mattsilver1** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging 9fb778c895d57c1c8541d1374e152adae33023d4 into ca1d3cd33fd457ade3c27902a2899ec4337f78c2 - [view on LGTM.com](https://lgtm.com/projects/g/FCCouncil/ShadowShard/rev/pr-4ca9f39144c061fd7924938ef86666d0708c32e6)

**new alerts:**

* 1 for Syntax error

**fixed alerts:**

* 1 for Expression has no effect

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by mattsilver1** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging 9fb778c895d57c1c8541d1374e152adae33023d4 into ddfaf339180b4503eef53bf6a13c38a4856c18c9 - [view on LGTM.com](https://lgtm.com/projects/g/FCCouncil/ShadowShard/rev/pr-fc8f75d3b38176f9ef1b069dab915ad6c440df64)

**new alerts:**

* 1 for Syntax error

**fixed alerts:**

* 1 for Expression has no effect

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Review by skele27 — APPROVED** [review]
Uhh okay

**Comment by mattsilver1** [comment]
To be honest, I don't even remember what this PR is even for...

**Pull request closed without merging**
